-- begin C7RP_PARTY
alter table C7RP_PARTY add constraint FK_C7RP_PARTY_ON_LOCATION foreign key (LOCATION_ID) references C7RP_LOCATION(ID)^
create index IDX_C7RP_PARTY_ON_LOCATION on C7RP_PARTY (LOCATION_ID)^
-- end C7RP_PARTY
-- begin C7RP_INVITATION
alter table C7RP_INVITATION add constraint FK_C7RP_INVITATION_ON_PERSON foreign key (PERSON_ID) references C7RP_PERSON(ID)^
alter table C7RP_INVITATION add constraint FK_C7RP_INVITATION_ON_PARTY foreign key (PARTY_ID) references C7RP_PARTY(ID)^
create index IDX_C7RP_INVITATION_ON_PERSON on C7RP_INVITATION (PERSON_ID)^
create index IDX_C7RP_INVITATION_ON_PARTY on C7RP_INVITATION (PARTY_ID)^
-- end C7RP_INVITATION
